### ISSUE TITLE
explosion/steam/ice particles effects are being cloned but not destroyed

### ISSUE THREAD

**Issue by ConnorSewell01** [Rexuiem/PlatformPanicGame#14]
**Particles not Destroyed in Hierarchy Issue**

When a player combines the Fire and Health in either order, the Explosion particle effect instantiates in the hierarchy, but this new effect is not deleted form the hierarchy once it finishes. This also happens with both the Steam (Water and Fire combination) and the Ice (Water and Magic combination) effects.

**Version 017**

**To Reproduce**

1. Open the scene. 
2. Press the 'play' button.
3. Have player one shoot the fire effect at a platform using the Q key.
4. Have player one shoot the magic effect at the same platform using the E key.
5. Look at the Hierarchy
6. Repeat steps 3-5.

**Expected Behaviour**

The Explosion effect should spawn into the hierarchy, and then be deleted once it is finished.

**Desktop System**

Windows 10

**Comment by Rexuiem** [comment]
when you combine the fire and health. or health and fire effect. it instantiates the explosion particle effect in the hierarchy, but doesn't then delete it out of the hierarchy when it is finished. not massively urgent. BUT could cause unnecessary build up 

after second inspection, this issue is also occurring with the steam and ice particle effects.

(Saving the previous version as a comment here.)

**Comment by Metablu** [comment]
Bug fixed, Connor introduced code that destroys these particle effects and any of their duplicates once their purpose is served.
